### ISSUE TITLE
Cek kembali apa email terkirim saat pendaftaran kerjasama

### ISSUE THREAD

**Issue by FirlianiF** [OpenSID/wiki-layanan-opendesa#273]

**Comment by apidong** [comment]
```
ERROR - 2023-03-05 00:30:52 --> ErrorException: max(): Array must contain at least one element in /home/bangund1/Layanan_OpenDESA/app/Entities/PelangganEntity.php:120
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'max(): Array mu...', '/home/bangund1/...', 120, Array)
#1 /home/bangund1/Layanan_OpenDESA/app/Entities/PelangganEntity.php(120): max(Array)
#2 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/Entity/Entity.php(486): App\Entities\PelangganEntity->getTanggalBerlangganan()
#3 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/Entity/Entity.php(172): CodeIgniter\Entity\Entity->__get('tanggal_berlang...')
#4 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/Entity/Entity.php(397): CodeIgniter\Entity\Entity->toArray()
#5 [internal function]: CodeIgniter\Entity\Entity->jsonSerialize()
#6 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/Format/JSONFormatter.php(38): json_encode(Object(App\Entities\PelangganEntity), 832, 512)
#7 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/API/ResponseTrait.php(341): CodeIgniter\Format\JSONFormatter->format(Object(App\Entities\PelangganEntity))
#8 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/API/ResponseTrait.php(99): CodeIgniter\RESTful\ResourceController->format(Object(App\Entities\PelangganEntity))
#9 /home/bangund1/Layanan_OpenDESA/app/Controllers/API/PelangganController.php(68): CodeIgniter\RESTful\ResourceController->respond(Object(App\Entities\PelangganEntity))
#10 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/CodeIgniter.php(898): App\Controllers\API\PelangganController->pemesananPelanggan()
#11 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/CodeIgniter.php(468): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\API\PelangganController))
#12 /home/bangund1/Layanan_OpenDESA/vendor/codeigniter4/framework/system/CodeIgniter.php(351): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#13 /home/bangund1/Layanan_OpenDESA/public/index.php(55): CodeIgniter\CodeIgniter->run()
#14 {main}
ERROR - 2023-03-05 00:31:50 --> Tidak dapat mengirim surel menggunakan PHP mail(). Server Anda mungkin tidak dikonfigurasi untuk mengirim surel menggunakan metode ini.<br /><pre>Date: Sun, 5 Mar 2023 00:31:47 +0700

From: &quot;Layanan OpenDESA&quot; &lt;info@layanan.opendesa.id&gt;

Return-Path: &lt;info@layanan.opendesa.id&gt;

Reply-To: &lt;info@layanan.opendesa.id&gt;

User-Agent: CodeIgniter

X-Sender: info@layanan.opendesa.id

X-Mailer: CodeIgniter

X-Priority: 3 (Normal)

Message-ID: &lt;640380831fd533.93728983@layanan.opendesa.id&gt;

Mime-Version: 1.0

Content-Type: multipart/alternative; boundary=&quot;B_ALT_640380831fd856.17311057&quot;
=?UTF-8?Q?Verifikasi=20Alamat=20Email?=
This is a multi-part message in MIME format.

Your email application may not support this format.

```

**Comment by FirlianiF** [comment]
Sudah dicoba menggunakan mailtrap , email berhasil masuk, akan dipastikan data smpt nya sudah betul atau belum k pak rudi

**Comment by scqolbu24** [comment]
sudah dikerjakan melalui PR https://github.com/OpenSID/Layanan_OpenDESA/pull/226
